### PR TITLE
Working signups on backend

### LINKED ISSUE #27: Signup Page Backend (Create new users)
- Need to use the counter cluster to find current id, use that for new user, then increment that curr_user_id field 
- Store: user_id, username, password, the current timestamp, bio (set to none for now), and if they are an admin

### PR DESCRIPTION
**Pull request by JCresent**
Test signup page and see if you can create a user. 

### Steps to run:
1. Start backend in one terminal:
```
cd server
npm install
node index.js  
```
2. Start react (frontend) in another terminal (may prompt to run the frontend on another port since we also use 3000 for server, just say y): 
```
cd ronr_web_app
npm install
npm start 
```
3. Navigate to register page and create an account    
4. Should have output in server terminal:
image
5. Check the database to make sure new user was created (may take a minute and you may need to refresh or reconnect)
image

### CODE REVIEW

**Comment by ajarnold920** [comment]
Looks good, i successfully created a user in the database. 

After I hit register, it took me to a page that had some text at the top (with an option for pretty print)? I feel like this is a problem with my setup but idk.

**Review by ajarnold920 — DISMISSED** [review]
See comment.

**Comment by JCresent** [comment]
Check to now make sure passwords match, email is correct email format (test@test.com), and password strength is good (tells you what you need).

**Review by ajarnold920 — APPROVED** [review]
LGTM. Everything you texted me works.

**Pull request merged**
